import type { Metadata } from "next";
import { Roboto_Slab as Roboto } from "next/font/google";
import { AI } from "./ai";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AI>
      <html lang="en" suppressHydrationWarning className="scroll-smooth">
        <body
          className={`${roboto.variable} antialiased font-roboto scroll-smooth`}
          suppressHydrationWarning
        >
          {children}
        </body>
      </html>
    </AI>
  );
}
